### ISSUE TITLE
I am using Qt 5.12.0 and I get a 'qsizetype' error.

### ISSUE THREAD

**Issue by creeper-0910** [lumina-desktop/lumina#767] opened 2021-07-31 05:40 UTC
When I looked into it before, I was told that I could avoid the 'qsizetype' error by using Qt after 5.11, but my build is generating the same error.
![image](https://user-images.githubusercontent.com/56744841/127730048-2dbe54b2-9a22-4611-815c-9cc304fc6a96.png)

**Comment by antis81** [comment] 2021-08-08 08:29
Please make sure you have at least latest LTS Qt version installed (5.12.x). I'd personally recommend the latest "stable" (which is Qt 5.15.x).

If that doesn't fix the issue already:

```c++
#include <QtGlobal>
```

**Comment by BrianA-MN** [comment] 2021-10-04 03:19
The build dependency is qt5.4+.  But the error codes are for qt features that are introduced in 5.10 or 5.12?  Is anyone working to update the github documentation then?

**Comment by q5sys** [comment] 2021-10-04 03:38
@BrianA-MN I need to run a run through the documentation and get it up to date.  It's on the todo list, just haven't quite gotten to it yet.

**Comment by BrianA-MN** [comment] 2021-10-04 15:07
Thank you for taking on the maintenance of this project.   You've taken on a huge task and I'd help if Lumina desktop is beneficial to older machines.  I guess my statement was more of a question, i.e. does Lumina 1.6.x require a newer version of QT?

I have pulled a built copy of Lumina 1.4.0 from AlienBob's repository which runs under Slackware 14.2 with QT 5.9.6 and qt-webkit 5.7.1.  I've received a built copy of 1.6.0 from the Slackbuild maintainer and will try that soon.

**Comment by q5sys** [comment] 2021-10-08 15:00
> I guess my statement was more of a question, i.e. does Lumina 1.6.x require a newer version of QT?
It shouldn't need anything newer than 5.12  My build box is 5.15, but I haven't added any structural code changes that should require it.

> I'm trying to use keepass and can't get it to show in the systemtray when minimized.
I dont use keepass, I'll have to try to install it and see if I can reproduce your findings.

> BTW how can I get the background, minimized windows to show based on a mouse button3 or other method?
Ooh, that's a good question.  Since we're still using Fluxbox we're limited by what features it allows.  You would configure that in the fluxbox keys file.  You should be able to use `xev` to capture how the mouse buttons identify themselves and then use that as the modifier.  So if your middle button idenfities as 'Mouse2' for example, you'd add something like this to the fluxbox keys file: `Mouse2 :ToggleCmd {ShowDesktop}`  That 'should' hide/show all windows.  so depending on your current desktop you might have to hit it twice.  There may be a way to capture the state of the desktop and only show windows... but idk if that's possible.

On the slackware front, if there are patches in the slackbuilds scripts that you think might be able to be dealt with upstream (so long as they dont break things for every other distro and the BSDs) let me know. I'd like to get as much of that done upstream as possible.

**Comment by q5sys** [comment] 2021-11-15 00:10
Update docs to update the statement of needing qt 5.4 to needing 5.12.x with https://github.com/lumina-desktop/lumina/commit/77e6449d870eb12f24d5dca1b44ef6d6809d6b7a

**Comment by q5sys** [comment] 2021-11-15 00:11
Im going to close this ticket as I think I answered all your questions and I got the docs updated.  If in my re-read of this I missed something and you still have an issue or still have a question, please open another ticket for me to track.

**Closed by q5sys** 2021-11-15 00:11 UTC

**Comment by creeper-0910** [comment] 2021-11-15 03:18
Sorry, I've been away from here for a bit.
Thank you for resolving this!
