### ISSUE TITLE
Keybord Shortcuts bug

### ISSUE THREAD

**Issue by Kinouuu** [lumina-desktop/lumina#667] opened 2019-02-20 14:02 UTC
Hi everyone!

lumina-desktop/fluxbox-keys

When I want to set "F11" with volume down: it works with the blinding key method.
When I want to set "F12" with volume up: I'm blinding the key, I see something flicking but the key is not saved as shortcut. BUT I can set F12 with volume up in the advanced editor. The brand new shortcut is not reported in the basic editor. 

Did anyone experiment that?

**Comment by beanpole135** [comment] 2020-04-03 13:30
Closing this issue. Unable to reproduce, and seems like nobody else can either.

**Closed by beanpole135** 2020-04-03 13:30 UTC
