### ISSUE TITLE
Error by make : ubuntu18.04

### ISSUE THREAD

**Issue by uralrabo** [lumina-desktop/lumina#711] opened 2019-12-13 10:28 UTC
../libLumina/LuminaX11.cpp: In member function ‘QIcon LXCB::WindowIcon(WId)’:
../libLumina/LuminaX11.cpp:501:6: error: ‘qsizetype’ was not declared in this scope
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
      ^~~~~~~~~
../libLumina/LuminaX11.cpp:501:6: note: suggested alternative: ‘iswctype’
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
      ^~~~~~~~~
      iswctype
../libLumina/LuminaX11.cpp:501:21: error: ‘i’ was not declared in this scope
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
                     ^
../libLumina/LuminaX11.cpp:501:29: error: ‘class QImage’ has no member named ‘sizeInBytes’
  for(qsizetype i=0; i<image.sizeInBytes()/4; ++i, ++dat){
                             ^~~~~~~~~~~
../libLumina/LuminaX11.cpp: In member function ‘void LXCB::paintRoot(QRect, const QPixmap*)’:
../libLumina/LuminaX11.cpp:550:12: error: ‘class QImage’ has no member named ‘sizeInBytes’
  0, qimage.sizeInBytes(), qimage.bits());
            ^~~~~~~~~~~
Makefile:1386: recipe for target '.build/obj/LuminaX11.o' failed
make[3]: *** [.build/obj/LuminaX11.o] Error 1
make[3]: Verzeichnis „/home/ralf/lumina/src-qt5/core/lumina-desktop“ wird verlassen
Makefile:49: recipe for target 'sub-lumina-desktop-make_first' failed
make[2]: *** [sub-lumina-desktop-make_first] Error 2
make[2]: Verzeichnis „/home/ralf/lumina/src-qt5/core“ wird verlassen
Makefile:46: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Verzeichnis „/home/ralf/lumina/src-qt5“ wird verlassen
Makefile:44: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2

**Comment by lbartoletti** [comment] 2019-12-13 12:40
Duplicate of https://github.com/lumina-desktop/lumina/issues/710 ?

**Comment by beanpole135** [comment] 2019-12-13 18:15
Indeed. If you want to build Lumina with an old version of Qt (pre-5.10), you need to grab one of the releases and not build from the master branch.

**Closed by beanpole135** 2019-12-13 18:15 UTC
