### ISSUE TITLE
lumina-fm crashes on external updates

### ISSUE THREAD

**Issue by kbartosik** [lumina-desktop/lumina#639] opened 2018-11-23 03:23 UTC
Way to reproduce:
1) Open lumina-fm
2) Open terminal emulator and compress file in a directory lumina-fm has open in a pane.
3) Issue: after compression has finished the pane goes into inactive state.
4) unzip the file - this time lumina-fm crashes and dumps a core

/var/log/messages shows:
Nov 23 04:10:58 lenovo kernel: pid 2229 (lumina-fm), uid 1001: exited on signal 11 (core dumped)
Nov 23 04:12:05 lenovo kernel: pid 3339 (lumina-fm), uid 1001: exited on signal 11 (core dumped)
Nov 23 04:13:16 lenovo kernel: pid 3858 (lumina-fm), uid 1001: exited on signal 6 (core dumped)

lumina-1.4.1,3
lumina-archiver-1.4.1
lumina-calculator-1.4.1
lumina-core-1.4.1
lumina-coreutils-1.4.1
lumina-fileinfo-1.4.1_1
lumina-fm-1.4.1
lumina-mediaplayer-1.4.1_1
lumina-pdf-1.4.1
lumina-screenshot-1.4.1
lumina-textedit-1.4.1_1

OS: FreeBSD 11.2-RELEASE-p4
[lumina-fm.core.gz](https://github.com/lumina-desktop/lumina/files/2609618/lumina-fm.core.gz)

**Comment by stackyjoe** [comment] 2018-11-23 20:56
I've had the same issue, though I can't reproduce it. Running lldb on my core file shows:

`* thread #1, name = 'lumina-fm', stop reason = signal SIGSEGV
  * frame #0: 0x0000000802b31573 libQt5Core.so.5`QString::section(QString const&, int, int, QFlags<QString::SectionFlag>) const + 67
    frame #1: 0x000000000044cce6 lumina-fm`___lldb_unnamed_symbol54$$lumina-fm + 422
    frame #2: 0x00000000004f0d99 lumina-fm`BrowserWidget::loadStatistics(BrowserWidget*) + 89
    frame #3: 0x00000000004eb8b0 lumina-fm`___lldb_unnamed_symbol517$$lumina-fm + 48
    frame #4: 0x0000000802aab09d libQt5Core.so.5`___lldb_unnamed_symbol227$$libQt5Core.so.5 + 109
    frame #5: 0x0000000802ab31ab libQt5Core.so.5`___lldb_unnamed_symbol279$$libQt5Core.so.5 + 235
    frame #6: 0x0000000803cb0c06 libthr.so.3`thread_start(curthread=0x000000081a447000) at thr_create.c:289
`
I'm guessing somehow one of the QString::prepend or QString::arg calls in BrowserWidget::loadStatistics is getting a reference to a null string somehow.

**Comment by beanpole135** [comment] 2019-04-03 11:50
This appears to be fixed in the current version from source.

**Closed by beanpole135** 2019-04-03 11:50 UTC
