### ISSUE TITLE
Unstable running Lumina on FreeBSD with scfb video driver

### ISSUE THREAD

**Issue by dpostolov** [lumina-desktop/lumina#668] opened 2019-02-24 06:41 UTC
Hi to all! Sorry for my bad English...
Unstable running Lumina on FreeBSD with scfb video driver. Hardware: Intel NUC 5PPYH Braswell. If to install FreeBSD-12.0 or CURRENT and to add to rc.conf "dbus_enable="YES"", then install Lumina-DE from pkg, I can run Lumina with command "start-lumina-desktop".

But this successfull run is unstable. Sometimes Lumina force back to system console on startup, if scfb video driver configured in /usr/local/etc/X11/xorg.conf.d/scfb-driver.conf:

Section "Device"
 Identifier "Card0"
 Driver "scfb"
EndSection

No this problem if intel video driver is installed and configured.

**Comment by beanpole135** [comment] 2019-02-25 13:09
On your FreeBSD system, please try running this command from the terminal:
`sysctl machdep.bootmethod`
If it returns "BIOS", then the scfb driver cannot be used, you will need to use the vesa driver. The scfb driver can only be used on FreeBSD if the bootmethod is "UEFI"

Closing this issue as a FreeBSD issue, not related to Lumina.

**Closed by beanpole135** 2019-02-25 13:09 UTC

**Comment by dpostolov** [comment] 2019-02-25 14:13
dmitry@nuc5:~ % sysctl machdep.bootmethod
machdep.bootmethod: UEFI

**Comment by beanpole135** [comment] 2019-02-25 14:15
You will need to grab the xorg logs and see what is causing X to not start up: /var/log/Xorg.0.log
Once you determine the cause of the failure, then you will need to adjust your configs as necessary.
